name: Ruby

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and test with Rake
      env:
        DB_NAME: db_bike_api
        DB_USERNAME: hideki
        DB_PASSWORD: db_bike_api
        DB_TEST_NAME: db_test_bike_api
        DB_TEST_USERNAME: hideki
        DB_TEST_PASSWORD: db_bike_api
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        ruby -v
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
        working-directory: ./src
        bin/rails db:create
          bin/rails db:schema:load
        rubocop
        bundle exec rspec
