name: Ruby

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          DB_USERNAME: hideki
          DB_PASSWORD: db_bike_api
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          DB_TEST_NAME: db_test_bike_api
          DB_TEST_USERNAME: hideki
          DB_TEST_PASSWORD: db_bike_api
          DATABASE_URL: postgresql://postgres@localhost:5432/postgres?encoding=utf8&pool=5&timeout=5000
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Build DB
      run: |
        ruby -v
        cp config/database.yml.github-actions config/database.yml
        cat config/database.yml
        gem install bundler:2.0.2
        bundle update --bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:create
        bin/rails db:schema:load
        bin/rails db:migrate:reset RAILS_ENV=test
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    - name: Run Bundle
      run: |
        bundle update --bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Run Rubocop and Rspec
      run: 
        rubocop
        bundle exec rspec
