name: Ruby

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        env:
          DB_NAME: db_bike_api
          DB_USERNAME: hideki
          DB_PASSWORD: db_bike_api
          DB_TEST_NAME: db_test_bike_api
          DB_TEST_USERNAME: hideki
          DB_TEST_PASSWORD: db_bike_api
          DATABASE_URL: postgresql://postgres@localhost:5432/postgres?encoding=utf8&pool=5&timeout=5000
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and test with Rake
      
      run: |
        ruby -v
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
        working-directory: ./src
        bin/rails db:create
        in/rails db:schema:load
        bin/rails db:migrate:reset RAILS_ENV=test
        rubocop
        bundle exec rspec
