name: Ruby

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          DB_USERNAME: hideki
          DB_PASSWORD: db_bike_api
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          DB_TEST_NAME: db_test_bike_api
          DB_TEST_USERNAME: hideki
          DB_TEST_PASSWORD: db_bike_api
          DATABASE_URL: postgresql://postgres@localhost:5432/postgres?encoding=utf8&pool=5&timeout=5000
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    container:
      image: ruby:2.6.5
      env:
        RAILS_ENV: test
        RAILS_DATABASE_HOST: postgres # this is needed
        RAILS_DATABASE_USER: pguser
        RAILS_DATABASE_PASSWORD: password
    steps:
    - uses: actions/checkout@v1
    - name: Run Bundle
      run: |
        cp config/database.yml.github-actions config/database.yml
        cat config/database.yml
        gem install bundler:2.0.2
        bundle install --jobs 4 --retry 3
        puts "gem install bundler:2.0.2終了"
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    - name: Build DB
      run: |
        ruby -v
        bin/rails db:create
        bin/rails db:schema:load
        bin/rails db:migrate:reset RAILS_ENV=test
    - name: Run Rubocop and Rspec
      run: 
        rubocop
        bundle exec rspec
        